### ISSUE TITLE
add a rough curl equivalent to the readme

### ISSUE THREAD

**Issue by llimllib** [carlmjohnson/get-headers#4]
Here's as close as I could quickly come with curl:

```shell
$ curl -sD - -o /dev/null -w 'time: %{time_total}s\ndownload speed: %{speed_download} bytes/s' https://httpbingo.org
HTTP/2 200 
access-control-allow-credentials: true
access-control-allow-origin: *
content-security-policy: default-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' camo.githubusercontent.com
content-type: text/html; charset=utf-8
date: Wed, 06 Sep 2023 20:58:38 GMT
server: Fly/8770e2a7 (2023-09-01)
via: 2 fly.io
fly-request-id: 01H9P4ME7AH00SGSZN7RCS55VY-lga

time: 0.127817s
content length: 89894 bytes/s
```

Unfortunately content-length is not available as a [write-out variable](https://curl.se/docs/manpage.html#-w).

I'm not suggesting this replaces `get-headers`, but it might be worth putting a close curl equivalent in the docs? up to you.

**Comment by earthboundkid** [comment]
I probably wouldn’t have made this if I had known about `curl -IXGET`, but it’s made now. I’m not sure anyone else uses it?

**Comment by llimllib** [comment]
hah, no worries - I only saw it because it came up on my github feed

**Comment by earthboundkid** [comment]
Wow, this repo is only a month younger than my marriage.
